# Generated by Django 3.0.5 on 2020-04-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='作品名')),
                ('description', models.TextField(verbose_name='詳細説明')),
                ('release_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='リリース日')),
                ('maker', models.CharField(db_index=True, max_length=50, verbose_name='作り手')),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='更新日')),
                ('screen_name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='twitter ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Category', verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True, verbose_name='twitterからの詳細情報')),
                ('official_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='公式URL')),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='アイコン画像のURL')),
                ('banner_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='バナー画像のURL')),
                ('followers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='フォワー数')),
                ('all_tweet_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='取得したツイート数')),
                ('all_retweet_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='リツイート総数')),
                ('all_favorite_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='イイね総数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Content', verbose_name='作品')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.PositiveIntegerField(unique=True, verbose_name='ツイートID')),
                ('text', models.TextField(verbose_name='内容')),
                ('retweet_count', models.PositiveIntegerField(verbose_name='リツート数')),
                ('favorite_count', models.PositiveIntegerField(verbose_name='いいね数')),
                ('tweet_date', models.DateTimeField(verbose_name='ツイート日')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='ツイート取得日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='ツイート取得更新日')),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.TwitterUser', verbose_name='Twitterデータ')),
            ],
        ),
    ]
