# Generated by Django 3.0.5 on 2020-04-15 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='作品名')),
                ('description', models.CharField(max_length=500, verbose_name='詳細説明')),
                ('release_date', models.DateTimeField(db_index=True, verbose_name='リリース日')),
                ('maker', models.CharField(db_index=True, max_length=50, verbose_name='作り手')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_screen_name', models.CharField(max_length=255, unique=True, verbose_name='スクリーンネーム')),
                ('tw_description', models.CharField(max_length=500, verbose_name='twitterからの詳細情報')),
                ('content_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='公式URL')),
                ('profile_image_url_https', models.CharField(blank=True, max_length=500, null=True, verbose_name='アイコン画像のURL')),
                ('profile_banner_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='バナー画像のURL')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Content', verbose_name='作品名')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterRegularlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweet_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='リツイート総数')),
                ('favorite_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='いいね総数')),
                ('statuses_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='ツイート取得総数')),
                ('listed_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='リスト総数')),
                ('followers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='フォワー数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='データ取得日')),
                ('tw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.TwitterData', verbose_name='Twitterデータ')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, unique=True, verbose_name='カテゴリー名')),
                ('contents', models.ManyToManyField(to='ranking.Content', verbose_name='作品名')),
            ],
        ),
    ]
