# Generated by Django 3.0.5 on 2020-04-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='作品名')),
                ('description', models.CharField(max_length=500, verbose_name='詳細説明')),
                ('release_date', models.DateTimeField(db_index=True, verbose_name='リリース日')),
                ('maker', models.CharField(db_index=True, max_length=50, verbose_name='作り手')),
                ('tweets_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='ツイート総数')),
                ('aggregation_start_date', models.DateTimeField(blank=True, null=True, verbose_name='集計開始日')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets_count', models.PositiveIntegerField(default=0, verbose_name='ツイート数')),
                ('aggregation_period', models.DateTimeField(verbose_name='集計期間')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Content', verbose_name='作品名')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, unique=True, verbose_name='カテゴリー名')),
                ('content', models.ManyToManyField(to='ranking.Content', verbose_name='作品名')),
            ],
        ),
    ]
