# Generated by Django 3.0.5 on 2020-04-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(verbose_name='詳細説明'),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='tw_description',
            field=models.TextField(verbose_name='twitterからの詳細情報'),
        ),
    ]
