# Generated by Django 3.0.5 on 2020-04-10 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='aggregation_period',
            field=models.DurationField(verbose_name='集計期間'),
        ),
    ]
