# Generated by Django 3.0.5 on 2020-04-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ranking.Content', verbose_name='作品'),
        ),
    ]
