# Generated by Django 3.0.5 on 2020-04-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20200416_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='リリース日'),
        ),
    ]
