# Generated by Django 3.0.5 on 2020-04-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20200413_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterdata',
            name='aggregation_period',
            field=models.DateTimeField(verbose_name='集計日'),
        ),
    ]
