# Generated by Django 3.0.5 on 2020-04-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_auto_20200420_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='all_favorite_count',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='all_retweet_count',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='all_tweet_count',
        ),
    ]
