# Generated by Django 3.0.5 on 2020-04-14 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20200413_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='aggregation_start_date',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tweets_total',
        ),
        migrations.RemoveField(
            model_name='twitterdata',
            name='aggregation_period',
        ),
        migrations.RemoveField(
            model_name='twitterdata',
            name='tweets_count',
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='content_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='公式URL'),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='profile_banner_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='バナー画像のURL'),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='profile_image_url_https',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='アイコン画像のURL'),
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='tw_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='twitterからの詳細情報'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='tw_screen_name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='スクリーンネーム'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TwitterRegularlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweet_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='リツイート総数')),
                ('favorite_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='いいね総数')),
                ('statuses_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='ツイート取得総数')),
                ('listed_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='リスト総数')),
                ('followers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='フォワー数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='データ取得日')),
                ('tw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.TwitterData', verbose_name='Twitterデータ')),
            ],
        ),
    ]
