# Generated by Django 3.0.5 on 2020-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20200423_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='screen_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='twitter ID'),
        ),
    ]
