# Generated by Django 3.0.5 on 2020-04-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_auto_20200425_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='img_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='画像のURL'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('role', models.CharField(db_index=True, max_length=50)),
                ('is_cast', models.BooleanField(db_index=True, default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Content', verbose_name='作品')),
            ],
        ),
    ]
