# Generated by Django 3.0.5 on 2020-04-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_auto_20200427_1038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('name', 'role', 'content')},
        ),
    ]
