# Generated by Django 3.0.5 on 2020-04-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0010_auto_20200427_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='all_favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='いいね総数'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='all_retweet_count',
            field=models.PositiveIntegerField(default=0, verbose_name='リツイート総数'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='all_tweet_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ツイート総数'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='フォワー数'),
        ),
    ]
