# Generated by Django 3.0.5 on 2020-04-27 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0011_auto_20200427_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweet_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='update_date',
        ),
        migrations.CreateModel(
            name='TweetCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweet_count', models.PositiveIntegerField(verbose_name='リツート数')),
                ('favorite_count', models.PositiveIntegerField(verbose_name='いいね数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='ツイート取得日')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Tweet', verbose_name='ツイート')),
            ],
        ),
    ]
